# Generated by Django 5.0.6 on 2024-05-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_nascimento',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
