# Generated by Django 5.0.6 on 2024-05-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0002_paciente_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='convenio_medico',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='especialidade',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='forma_pagamento',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
