# Generated by Django 5.0.6 on 2024-05-30 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0003_paciente_convenio_medico_paciente_especialidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='data_consulta',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
