# Generated by Django 5.0.6 on 2024-05-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0004_paciente_data_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='convenio_medico',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_consulta',
            field=models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especialidade',
            field=models.CharField(choices=[('Clinico Geral', 'Clinico Geral'), ('Oftalmologista', 'Oftalmologista'), ('Dermatologista', 'Dermatologista')], default='Clinico Geral', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='forma_pagamento',
            field=models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de credito', 'Cartão de credito'), ('Cartão de debito', 'Cartão de debito'), ('Convênio médico', 'Convênio médico')], default='Dinheiro', max_length=50),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='prioridade',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=5),
        ),
    ]
