# Generated by Django 5.0.6 on 2024-06-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador', '0005_alter_paciente_convenio_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacienteFilaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fila', models.CharField(max_length=100)),
                ('endereco_fila', models.CharField(max_length=100)),
                ('prioridade_fila', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=5)),
                ('cpf_fila', models.CharField(max_length=15)),
                ('rg_fila', models.CharField(max_length=15)),
                ('telefone_fila', models.CharField(max_length=20)),
                ('email_fila', models.CharField(max_length=100)),
                ('data_nascimento_fila', models.DateField()),
                ('especialidade_fila', models.CharField(choices=[('Clinico Geral', 'Clinico Geral'), ('Oftalmologista', 'Oftalmologista'), ('Dermatologista', 'Dermatologista')], default='Clinico Geral', max_length=50)),
                ('data_consulta_fila', models.CharField(choices=[('Segunda-feira', 'Segunda-feira'), ('Terça-feira', 'Terça-feira'), ('Quarta-feira', 'Quarta-feira'), ('Quinta-feira', 'Quinta-feira'), ('Sexta-feira', 'Sexta-feira')], max_length=50)),
                ('convenio_medico_fila', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=50)),
                ('forma_pagamento_fila', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de credito', 'Cartão de credito'), ('Cartão de debito', 'Cartão de debito'), ('Convênio médico', 'Convênio médico')], default='Dinheiro', max_length=50)),
            ],
        ),
    ]
